"""Hardware execution interfaces for robot adapters."""

from typing import Protocol

from src.motion.types import MotionPlan


class RobotArmInterface(Protocol):
    """Interface implemented by concrete robot adapters/drivers."""

    def connect(self) -> None: ...
    def disconnect(self) -> None: ...
    def home(self) -> None: ...
    def execute_motion_plan(self, plan: MotionPlan) -> None: ...
    def send_joint_positions(self, joint_targets_deg: dict[str, float], speed_mm_s: float | None = None) -> None: ...
    def open_gripper(self) -> None: ...
    def close_gripper(self) -> None: ...
